/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.main;

import com.utils.FormData;
import com.utils.Utilidades;
import java.awt.Color;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ConfirmationForm extends javax.swing.JDialog {

    /**
     * Creates new form ConfirmationForm
     */
    
    private FormData datos;
    public ConfirmationForm(java.awt.Frame parent, boolean modal, FormData datos) {
        super(parent, modal);
        this.datos = datos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bn_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_msg = new javax.swing.JTextArea();
        btn_exit = new javax.swing.JButton();
        bg_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        bn_panel.setBackground(new java.awt.Color(255, 255, 255));
        bn_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_msg.setEditable(false);
        user_msg.setOpaque(true);
        user_msg.setBackground(new Color(235, 235, 235, 170));
        user_msg.setColumns(20);
        user_msg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_msg.setRows(5);
        user_msg.setBorder(null);
        user_msg.setFocusable(false);
        jScrollPane1.setViewportView(user_msg);
        String mensaje = "Muchas gracias " + datos.getNombre() +
        ".\nSe ha confirmado tu cita para el día \n" +
        Utilidades.formatearFecha(datos.getFecha())
        + " a las " + Utilidades.formatearHora(datos.getHora());
        user_msg.setText(mensaje);

        bn_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 330, 190));
        jScrollPane1.setBorder(null);

        btn_exit.setText("Aceptar");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        bn_panel.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, 30));

        bg_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/notification-background.jpg"))); // NOI18N
        bn_panel.add(bg_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 400, 310));
        ImageIcon iconoOriginal = (ImageIcon) bg_image.getIcon();
        Image imagen = iconoOriginal.getImage();
        Image imagenReescalada = imagen.getScaledInstance(400, 300, java.awt.Image.SCALE_SMOOTH);
        ImageIcon iconoReescalado = new ImageIcon(imagenReescalada);
        bg_image.setIcon(iconoReescalado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bn_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bn_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormData datos = new FormData("nombre", new Date(), new Date());
                ConfirmationForm dialog = new ConfirmationForm(new javax.swing.JFrame(), true, datos);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_image;
    private javax.swing.JPanel bn_panel;
    private javax.swing.JButton btn_exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea user_msg;
    // End of variables declaration//GEN-END:variables
}
