/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.main;

/**
 *
 * @author Angeles
 */
public class FormModal extends javax.swing.JDialog {

    /**
     * Creates new form FormModal
     */
    public FormModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_bg = new javax.swing.JPanel();
        form_data = new javax.swing.JPanel();
        form_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_number = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        input_name = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        input_email = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        main_bg.setBackground(new java.awt.Color(255, 255, 255));
        main_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form_data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form_title.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        form_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        form_title.setText("Datos del contacto");
        form_data.add(form_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, -1));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel1.setLabelFor(input_name);
        jLabel1.setText("NOMBRE");
        jLabel1.setToolTipText("Introduce nombre y apellidos");
        form_data.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 20));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel4.setLabelFor(input_email);
        jLabel4.setText("EMAIL");
        jLabel4.setToolTipText("Introduce email");
        form_data.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 280, 20));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel5.setLabelFor(input_number);
        jLabel5.setText("TELEFONO");
        jLabel5.setToolTipText("Introduce telefono");
        form_data.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 20));

        jScrollPane1.setViewportView(input_number);

        form_data.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 30));

        jScrollPane2.setViewportView(input_name);

        form_data.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 30));

        jScrollPane3.setViewportView(input_email);

        form_data.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, 30));

        main_bg.add(form_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, 300));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        main_bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormModal dialog = new FormModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel form_data;
    private javax.swing.JLabel form_title;
    private javax.swing.JTextPane input_email;
    private javax.swing.JTextPane input_name;
    private javax.swing.JTextPane input_number;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel main_bg;
    // End of variables declaration//GEN-END:variables
}
