/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import com.utils.Utilidades;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Angeles
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu_bg = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        brand_name = new javax.swing.JLabel();
        tag = new javax.swing.JLabel();
        main_bg = new javax.swing.JPanel();
        main_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(204, 255, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_bg.setBackground(new java.awt.Color(204, 204, 204));
        menu_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_start.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btn_start.setText("Realizar reserva");
        btn_start.setToolTipText("Realiza una reserva");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        menu_bg.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 160, -1));

        brand_name.setFont(new java.awt.Font("French Script MT", 0, 48)); // NOI18N
        brand_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand_name.setText("Salón principal");
        menu_bg.add(brand_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 280, 80));

        tag.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        tag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tag.setText("Restaurante");
        menu_bg.add(tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, -1));

        bg.add(menu_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        main_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/portada.jpg"))); // NOI18N
        main_bg.add(main_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
        // Ajustar la imagen después de que se haya creado el JLabel
        ImageIcon iconoOriginal = (ImageIcon) main_image.getIcon();
        Image imagen = iconoOriginal.getImage();
        Image imagenReescalada = imagen.getScaledInstance(500, 500, java.awt.Image.SCALE_SMOOTH);
        ImageIcon iconoReescalado = new ImageIcon(imagenReescalada);
        main_image.setIcon(iconoReescalado);

        bg.add(main_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        FormModal modal = new FormModal(null, true);
        Utilidades.openModal(modal);
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel brand_name;
    private javax.swing.JButton btn_start;
    private javax.swing.JPanel main_bg;
    private javax.swing.JLabel main_image;
    private javax.swing.JPanel menu_bg;
    private javax.swing.JLabel tag;
    // End of variables declaration//GEN-END:variables
}
