
package com.main;

import com.utils.Utilidades;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    int mouseX, mouseY;
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu_bg = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        brand_name = new javax.swing.JLabel();
        tag = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        main_bg = new javax.swing.JPanel();
        main_image = new javax.swing.JLabel();
        menu_principal = new javax.swing.JMenuBar();
        option1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(204, 255, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_bg.setBackground(new java.awt.Color(204, 204, 204));
        menu_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_start.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btn_start.setText("Realizar reserva");
        btn_start.setToolTipText("Realiza una reserva");
        btn_start.setBorder(null);
        btn_start.setBorderPainted(false);
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        menu_bg.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 160, 40));

        brand_name.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        brand_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand_name.setText("Salón principal");
        menu_bg.add(brand_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 280, 80));

        tag.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        tag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tag.setText("Restaurante");
        menu_bg.add(tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, -1));

        btn_exit.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btn_exit.setText("Salir");
        btn_exit.setToolTipText("Realiza una reserva");
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        menu_bg.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 160, 40));

        bg.add(menu_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        main_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/portada.jpg"))); // NOI18N
        main_bg.add(main_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
        // Ajustar la imagen después de que se haya creado el JLabel
        ImageIcon iconoOriginal = (ImageIcon) main_image.getIcon();
        Image imagen = iconoOriginal.getImage();
        Image imagenReescalada = imagen.getScaledInstance(500, 500, java.awt.Image.SCALE_SMOOTH);
        ImageIcon iconoReescalado = new ImageIcon(imagenReescalada);
        main_image.setIcon(iconoReescalado);

        bg.add(main_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 500, 500));

        menu_principal.setBorder(null);
        menu_principal.setBorderPainted(false);
        menu_principal.setOpaque(true);

        option1.setText("Iniciar reserva");
        option1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        option1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        option1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                option1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                option1MouseExited(evt);
            }
        });
        option1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1ActionPerformed(evt);
            }
        });
        menu_principal.add(option1);

        setJMenuBar(menu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        FormModal modal = new FormModal(null, true);
        Utilidades.openModal(modal);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option1ActionPerformed

    private void option1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option1MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        FormModal modal = new FormModal(null, true);
        Utilidades.openModal(modal);
    }//GEN-LAST:event_option1MouseClicked

    private void option1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option1MouseEntered
     
    }//GEN-LAST:event_option1MouseEntered

    private void option1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option1MouseExited
     
    }//GEN-LAST:event_option1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel brand_name;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_start;
    private javax.swing.JPanel main_bg;
    private javax.swing.JLabel main_image;
    private javax.swing.JPanel menu_bg;
    private javax.swing.JMenuBar menu_principal;
    private javax.swing.JMenu option1;
    private javax.swing.JLabel tag;
    // End of variables declaration//GEN-END:variables
}
